'''
    You will only be writing code in this file and this is the only file submitted to the autograder.
'''
import sys
import csv

def get_version():
    '''
        return the version of python that you are using.
    '''
    "*** WRITE YOUR CODE HERE ***"
    version = sys.version
    return version.split()[0] #Split string to get only version number
    


def alternative_sum(start, n):
    '''
        modify the function to return a list with generated by an alternative sum sequence explained in the assignment handout
    '''
    "*** WRITE YOUR CODE HERE ***"
    if start <= 0 or ( n < 5) or ( n > 20):
        return []
    else:
        sum_arr = [start]
        for i in range(1, n):
            if i < 3:
                sum_arr.append(sum_arr[-1] + sum_arr[-1])   
            else:
                sum_arr.append(sum_arr[-1] + sum_arr[-3])   
    
    return sum_arr
    



def order_scores():
    '''
        read the files scores.csv in the data directory and return the list of names sorted in ascending order of the scores.
    '''
    "*** WRITE YOUR CODE HERE ***"
    with open('data/scores.csv', mode ='r')as file:
        csvFile = csv.reader(file)
        next(csvFile) 
        score_list = []
        for lines in csvFile:
            score_list.append((lines[0], int(lines[1])))
        score_list.sort(key=lambda x: x[1]) 
        sorted_names = [name for name, score in score_list] 
        return sorted_names
    
print(alternative_sum(4, 10))